export enum StyleCode {
  black = "§0",
  darkBlue = "§1",
  darkGreen = "§2",
  darkAqua = "§3",
  darkRed = "§4",
  darkPurple = "§5",
  gold = "§6",
  gray = "§7",
  darkGray = "§8",
  blue = "§9",
  green = "§a",
  aqua = "§b",
  red = "§c",
  lightPurple = "§d",
  yellow = "§e",
  white = "§f",
  minecoinGold = "§g",

  obfuscated = "§k",
  bold = "§l",
  italic = "§o",
  reset = "§r",
}
